### ISSUE TITLE
File transfer fails sometimes for large files ( ~500 MB)

### ISSUE THREAD

**Issue by prashanthps** [jbardin/scp.py#103]
Env:

```
ansible 2.4.3.0
  config file = /opt/symmetra/playbooks/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv/ansible/lib/python2.7/site-packages/ansible
  executable location = /opt/venv/ansible/bin/ansible
  python version = 2.7.10 (default, Feb 22 2018, 06:04:15) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

===================================================================
The full traceback is:
```
Traceback (most recent call last):
  File "/tmp/ansible_uSlFc7/ansible_module_box_manage_files.py", line 109, in <module>
    main()
  File "/tmp/ansible_uSlFc7/ansible_module_box_manage_files.py", line 103, in main
    if node.scp_file(src, dst, device_hostname, device_username, device_password):
  File "/tmp/ansible_uSlFc7/ansible_module_box_manage_files.py", line 41, in scp_file
    scp.put(src, dst)
  File "/opt/venv/ansible/lib/python2.7/site-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/opt/venv/ansible/lib/python2.7/site-packages/scp.py", line 250, in _send_files
    self._send_file(fl, name, mode, size)
  File "/opt/venv/ansible/lib/python2.7/site-packages/scp.py", line 276, in _send_file
    self._recv_confirm()
  File "/opt/venv/ansible/lib/python2.7/site-packages/scp.py", line 337, in _recv_confirm
    raise SCPException('Timeout waiting for scp response')
scp.SCPException: Timeout waiting for scp response

fatal: [host]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_uSlFc7/ansible_module_box_manage_files.py\", line 109, in <module>\n    main()\n  File \"/tmp/ansible_uSlFc7/ansible_module_box_manage_files.py\", line
103, in main\n    if node.scp_file(src, dst, device_hostname, device_username, device_password):\n  File \"/tmp/ansible_uSlFc7/ansible_module_box_manage_files.py\", line 41, in scp_file\n    scp.put(src, dst)\n  File \"/opt/venv/ans
ible/lib/python2.7/site-packages/scp.py\", line 154, in put\n    self._send_files(files)\n  File \"/opt/venv/ansible/lib/python2.7/site-packages/scp.py\", line 250, in _send_files\n    self._send_file(fl, name, mode, size)\n  File \
"/opt/venv/ansible/lib/python2.7/site-packages/scp.py\", line 276, in _send_file\n    self._recv_confirm()\n  File \"/opt/venv/ansible/lib/python2.7/site-packages/scp.py\", line 337, in _recv_confirm\n    raise SCPException('Timeout
 waiting for scp response')\nscp.SCPException: Timeout waiting for scp response\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

**Comment by prashanthps** [comment]
For smallish files (< 10MB) the chances of success are greater. Also, for connections that have an RTT of 30ms or greater, this failure happens more frequently.

**Comment by prashanthps** [comment]
But the strange thing is, file the Ansible module errors out with the error above, the actual file gets transferred fully... it just takes a bit longer because of the size of the file (~477 MB)

**Comment by prashanthps** [comment]
The file transfer succeeds perhaps 50% of the time, but when it fails, its always for the same reason: 
"/opt/venv/ansible/lib/python2.7/site-packages/scp.py", line 276, in _send_file\n self._recv_confirm()\n File "/opt/venv/ansible/lib/python2.7/site-packages/scp.py", line 337, in _recv_confirm\n raise SCPException('Timeout
waiting for scp response')\nscp.SCPException: Timeout waiting for scp response\n",

**Comment by prashanthps** [comment]
I was able to reproduce the error outside of the ansible environment.. on basic python shell.

```
Setup:
In [27]:     def scp_file(src, dst, hostname, username, password):
    ...:         ssh = paramiko.SSHClient()
    ...:         ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ...:         ssh.connect(hostname, username=username, password=password, timeout=150)
    ...:         scp = SCPClient(ssh.get_transport(), progress=progress)
    ...:         scp.put(src, dst)
    ...:         scp.close()
    ...:         ssh.close()
    ...:         return True
```
```
In [27]: def progress(filename, size, sent):
    ...:     print("%s\'s progress: %.2f%%   \r" % (filename, float(sent)/float(size)*100) )
    ...:
```
================================
...
b'EOS-4.17.6M.swi''s progress: 99.99%
b'EOS-4.17.6M.swi''s progress: 100.00%
b'EOS-4.17.6M.swi''s progress: 100.00%
---------------------------------------------------------------------------
PipeTimeout                               Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/paramiko/channel.py in recv(self, nbytes)
    682         try:
--> 683             out = self.in_buffer.read(nbytes, self.timeout)
    684         except PipeTimeout:

/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py in read(self, nbytes, timeout)
    159                         if timeout <= 0.0:
--> 160                             raise PipeTimeout()
    161

PipeTimeout:

During handling of the above exception, another exception occurred:

timeout                                   Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/scp.py in _recv_confirm(self)
    313         try:
--> 314             msg = self.channel.recv(512)
    315         except SocketTimeout:

/usr/local/lib/python3.6/site-packages/paramiko/channel.py in recv(self, nbytes)
    684         except PipeTimeout:
--> 685             raise socket.timeout()
    686

timeout:

During handling of the above exception, another exception occurred:

SCPException                              Traceback (most recent call last)
<ipython-input-26-33d72b2763ee> in <module>()
----> 1 scp_file(src, dst, host_list[0], username, password)

<ipython-input-25-0843951b06c7> in scp_file(src, dst, hostname, username, password)
      4     ssh.connect(hostname, username=username, password=password, timeout=150)
      5     scp = SCPClient(ssh.get_transport(), progress=progress)
----> 6     scp.put(src, dst)
      7     scp.close()
      8     ssh.close()

/usr/local/lib/python3.6/site-packages/scp.py in put(self, files, remote_path, recursive, preserve_times)
    152             self._send_recursive(files)
    153         else:
--> 154             self._send_files(files)
    155
    156         self.close()

/usr/local/lib/python3.6/site-packages/scp.py in _send_files(self, files)
    253             chan.sendall('\x00')
    254             file_hdl.close()
--> 255             self._recv_confirm()
    256
    257     def _chdir(self, from_dir, to_dir):

/usr/local/lib/python3.6/site-packages/scp.py in _recv_confirm(self)
    314             msg = self.channel.recv(512)
    315         except SocketTimeout:
--> 316             raise SCPException('Timout waiting for scp response')
    317         # slice off the first byte, so this compare will work in py2 and py3
    318         if msg and msg[0:1] == b'\x00':

SCPException: Timout waiting for scp response
================================

**Comment by remram44** [comment]
Have you tried simply increasing the timeout? Is the remote machine under load?

**Comment by prashanthps** [comment]
Yes, I did. The remote machine is not under load. the actual file gets fully transferred , as you can see in the progress func printout (progress: 100.00%) , and error is thrown right after that when teh _recv_confirm(self) is called. I have played with lots of timeout values, but that didn't make a difference.

**Comment by remram44** [comment]
The way the code works, `scp.py` writes all data to the socket's buffer using `sendall()`, then starts the 5 second countdown waiting for the reply. That reply will only be sent when the server actually gets all that data, writes it on disk, and sends the confirmation back.

The problem I see is that writing to the buffer might be immediate even though the machine might be done sending much later.

But increasing the timeout should fix that...

**Comment by prashanthps** [comment]
Hmm... I tried increasing socket_timeout to 10.. and it worked. Repeated test on 10 remote hosts.. all of them worked well. This looks promising, and I'll try to do some more tests..

**Comment by remram44** [comment]
We can probably increase the default, since 5 seconds is really low (timeouts are usually 10-20s).

**Comment by prashanthps** [comment]
Agreed. Also, all my tests have been successful after I increased the socket_timeout to 15s. This is great! Thanks a lot for your help.
