### ISSUE TITLE
putfo() fails for File objects

### ISSUE THREAD

**Issue by sudhartion** [jbardin/scp.py#115]
The [putfo()](https://github.com/jbardin/scp.py/blob/58d0df78614f66bf4502a53f660f5b302cdfe412/scp.py#L170) method of SCPClient calls the [getvalue()](https://github.com/jbardin/scp.py/blob/58d0df78614f66bf4502a53f660f5b302cdfe412/scp.py#L186) method of the file-like argument, to obtain the data size for the _send_file() method call. File objects don't have a getvalue() method, so this fails for those.

Going by the [docstring of putfo()](https://github.com/jbardin/scp.py/blob/58d0df78614f66bf4502a53f660f5b302cdfe412/scp.py#L174), this seems like a bug. Could the size be obtained some other way so that File objects are supported too?

Perhaps by doing fl.read() to obtain the data for the size, followed by fl.seek(0) to reset the pointer for further use of the file-like. This assumes that the file-like supports random access though.

**Comment by remram44** [comment]
Indeed, we need the size, to send it to the server. Unfortunately there is no standard way in the "file-like" protocol to get it.

Reading the whole thing into memory with `fl.read()` defeats the purpose, we might as well just accept `bytes` instead :thinking:

**Comment by sudhartion** [comment]
Isn't ```fl.getvalue()``` the same as ```fl.read()``` aside from file pointer movement?

There's also the option of using ```fl.seek(0, os.SEEK_END)``` followed by ```fl.tell()``` to get the size. That would avoid reading the data into memory, but I'm slightly uncertain of its accuracy, especially after coming across [this](https://wiki.sei.cmu.edu/confluence/display/c/FIO19-C.+Do+not+use+fseek()+and+ftell()+to+compute+the+size+of+a+regular+file).

**Comment by remram44** [comment]
You are right. Indeed this method only works with `io.BytesIO`. This is a big problem.

I think the `putfo()` method should take a `length` argument, and if it's empty, use `seek()` and `tell()` to get at the size.

**Comment by remram44** [comment]
I released version 0.12.0 with the fix. Thanks for your help!
