### ISSUE TITLE
Progress callback is broken in version 0.12.0 if it is a method

### ISSUE THREAD

**Issue by eldadr** [jbardin/scp.py#117]
This [commit](https://github.com/jbardin/scp.py/commit/7e1071560067a89766f3a4399cadddd21913474c#diff-3630d5c375dec68ec430f476b0995853) introduced a change that relies on `method.__code__.co_argcount` to check if the progress callback function expects `peername` or not. However, when the progress callback is a method, argcount includes self, and therefore it is incorrect, causing the code to crash or to ignore the progress callback (if reaching the else clause in `_progress_tracker`).

**Comment by remram44** [comment]
Oh no! Sorry about that. We can probably detect this case, and we should probably recommend a `**kwargs` in the docs to prevent such compatibility problems in the future.

**Comment by remram44** [comment]
cc @grzegorzcode

**Comment by remram44** [comment]
This doesn't seem too reliable. There is also the case of classmethods.

Maybe substract one if `isinstance(method, types.MethodType)`?

**Comment by remram44** [comment]
Fixed in v0.12.1

**Comment by eldadr** [comment]
Thanks for the quick fix!
