### ISSUE TITLE
Add stat function to get the statistics about the file

### ISSUE THREAD

**Issue by XVilka** [jbardin/scp.py#123]
Like in SFTP http://docs.paramiko.org/en/2.4/api/sftp.html

**Comment by remram44** [comment]
Hi @XVilka! Unfortunately I don't think the SCP protocol offers any way to do this. Let me know if I'm mistaken.

You can simply use SFTP or run `ls -l` via `ssh` to get this information.

**Comment by XVilka** [comment]
You are right, switching to SFTP is easier.
