### ISSUE TITLE
Getting an error on connecting

### ISSUE THREAD

**Issue by JesusFistus** [jbardin/scp.py#126]
C:\Users\Yannick PC\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
C:\Users\Yannick PC\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
C:\Users\Yannick PC\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())

**Comment by remram44** [comment]
This is unrelated to scp, it is a paramiko issue. See paramiko/paramiko#1369
