### ISSUE TITLE
how to upload the content of directory,excluding directory 

### ISSUE THREAD

**Issue by zffocussss** [jbardin/scp.py#133]
say I have a direcory, I just want to upload the 1.txt... 9.txt under directory "a"
a
├── 1.txt
├── 2.txt
├── 3.txt
├── 4.txt
├── 5.txt
├── 6.txt
├── 7.txt
├── 8.txt
└── 9.txt

**Comment by remram44** [comment]
`put()` accepts a list of names, so you can just pass that. To get that list you can use `os.listdir()` or `glob.glob()`.
