### ISSUE TITLE
Scp with regex

### ISSUE THREAD

**Issue by FrauElster** [jbardin/scp.py#143]
<details><summary>Off topic</summary>So I really wanted to fork it and provide a pull request, but I am starring at your code for a long time now and have no clue how it does what it does :D Like maybe a bit, but because you are doing the scp on top of the ssh, so you dont provide credentials within your backage Im kinda lost.</details>

Anyways, I would love to see the functionality to get / put files matching a regex.
On normal/command line scp it would work like [that](https://unix.stackexchange.com/questions/67055/how-to-scp-with-regular-expressions).

**Comment by remram44** [comment]
This is not supported by the protocol so I don't think it's likely to be added here.
