### ISSUE TITLE
Support streams

### ISSUE THREAD

**Issue by baterflyrity** [jbardin/scp.py#153]
Hi! Can someone add support for raw binary streams instead of reading/writting physical files?

I have a starting point [here](https://github.com/jbardin/scp.py/blob/db5aad819766ee1786de4d8c5f13de60f71f2184/scp.py#L428): simply add availability of passing stream as *file* parameter alongside with manually opening it every time.

**Comment by remram44** [comment]
Would wrapping the calls to `open()` in a member method help? That way you can override it in a subclass?

**Comment by baterflyrity** [comment]
@remram44 , can you explain more detailed what do you mean by wrapping?

**Comment by remram44** [comment]
Duplicate of #94
