### ISSUE TITLE
Freebsd (Juniper Junos) not happy with extra space in Secure Copy get 

### ISSUE THREAD

**Issue by ktbyers** [jbardin/scp.py#158]
I started running into this over the weekend and I tracked it down to changes in 0.13.4 (versus 0.13.3).

Junos (uses freebsd) is not happy when there is an extra space after `scp`

So it works fine when the `exec_command` is: `b'scp -f /var/tmp/test9.txt'`

But it fails when it is `b'scp  -f /var/tmp/test9.txt'` (two spaces between the scp and the -f)

See:

https://github.com/ktbyers/netmiko/issues/2339

I will probably see if I can do a PR on this.

**Comment by remram44** [comment]
Oh no! That's definitely not intended, I will make a bugfix release ASAP. This is definitely caused by #157.

**Comment by ktbyers** [comment]
Sounds good. Let me know when you have a fix and I can regression test it on my side.
