### ISSUE TITLE
Missing __init__.py file in the scp.py folder

### ISSUE THREAD

**Issue by juakali-networks** [jbardin/scp.py#193]
Please consider adding an empty  __init__.py file in the scp.py folder.

This helps classes in scp.py python file to be imported in other python projects.

This is a strict requirement in Python3.12 which comes with Ubuntu 24.04 LTS.

Adding the line "from scp.scp import SCPClient" in another python file will not work on Ubuntu 24.04 LTS unless an empty  __init__.py file is added in the scp.py main folder

**Comment by remram44** [comment]
scp.py is a file not a folder
