### ISSUE TITLE
Connection reset after sending a file without waiting before closing the connection

### ISSUE THREAD

**Issue by okraits** [jbardin/scp.py#194]
I'm sending a firmware image to a device with OpenWrt:

```
from paramiko import SSHClient, AutoAddPolicy
from scp import SCPClient
from time import sleep

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.set_missing_host_key_policy(AutoAddPolicy())
ssh.connect('192.168.1.3', username='root')

scp = SCPClient(ssh.get_transport())
scp.put('firmware.img', '/tmp/fw_migration.bin')
sleep(1)
ssh.close()
```

The problem is that I get the error `Error writing: Connection reset by peer` from dropbear on the device if I don't use `sleep(1)` before calling `ssh.close()`.

Am I doing something wrong or is this a bug? It looks like `scp.put('firmware.img', '/tmp/fw_migration.bin')` returns although the process isn't finished.

**Comment by remram44** [comment]
What if you close the SCPClient with `scp.close()`?

**Comment by okraits** [comment]
That doesn't make any difference. The connection reset appears unless I add the `sleep(1)` before calling any of the two `close()` methods.

**Comment by remram44** [comment]
I'm not sure there's anything else to be done, calling the close() methods will shutdown the channel and the connection cleanly. Unless you can get a reproducer I am going to have to assume that the server is defective.
