### ISSUE TITLE
Give enough information to the progress callback to display a progress bar

### ISSUE THREAD

**Issue by AdrienMatricon** [jbardin/scp.py#195]
When downloading/uploading a single file, the `progress` and `progress4` tell us how many bytes are involved in the transfer and how many were already transferred, so that works great and a progress bar can be displayed.

When downloading/uploading a directory, those callbacks tell us which file is being transferred and the individual progress of that file, but nothing of the overall transfer.

I don't know what's doable, but it would be nice to have a callback reporting the progress of the overall transfer, as in "3 of 10 files transferred" and "1857 bytes transferred of 656832 total"

**Comment by AdrienMatricon** [comment]
What do you mean?
I get that when sending a directory I can look up its contents ahead of time, but how would you do that when receiving files?

**Comment by remram44** [comment]
I don't think there is a way for this library to know that either.
