### ISSUE TITLE
Windows - get method - OSError: [WinError 1] Incorrect function

### ISSUE THREAD

**Issue by pini-gh** [jbardin/scp.py#198]
Hi,

I'm experiencing this issue on Windows with scp.py 14.5 (embedded into an external product). Here is my testcase:
```
from paramiko import SSHClient
from scp import SCPClient

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect('example.com')

scp = SCPClient(ssh.get_transport())
scp.get('/home/user/mydata', recursive=True)
```

And the error:
```
Traceback (most recent call last):
  File "./test_scp.py", line 11, in <module>
    scp.get('/home/user/mydata', recursive=True)
  File "C:\Program Files\python\lib\site-packages\scp.py", line 281, in get
    self._recv_all()
  File "C:\Program Files\python\lib\site-packages\scp.py", line 436, in _recv_all
    command[code](msg[1:])
  File "C:\Program Files\python\lib\site-packages\scp.py", line 507, in _recv_file
    os.utime(path, self._utime)
OSError: [WinError 1] Incorrect function
```
Here example.com is a Linux server, `mydata` is a directory and the test case is run into the `C:\Temp` folder. My Windows environment is a Virtualbox VM running on a Linux box.

The only related issue I found is https://stackoverflow.com/questions/72603982/oserror-winerror-1-incorrect-function. But there are no external device involved in my case.

**Comment by remram44** [comment]
I can't reproduce this. I suggest trying to call `os.utime()` to see if that shows the issue. Either way it is unlikely that this is caused by anything in this library.

**Comment by pini-gh** [comment]
The error was triggered by an empty file named `NUL` on the Linux side.

**Comment by remram44** [comment]
Ah, yes, there are some file names like NUL and AUX that will break on Windows, even with a file extension.

You might be able to work around this by using [UNC paths](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths), for example `scp.get('/home/user/mydata', '\\\\?\\C:\\Temp', recursive=True)`
