### ISSUE TITLE
wildcards work?

### ISSUE THREAD

**Issue by stonefury** [jbardin/scp.py#48]
def get(self, remote_path, local_path='',
            recursive=False, preserve_times=False):
        """
        Transfer files from remote host to localhost

        @param remote_path: path to retreive from remote host. since this is
            evaluated by scp on the remote host, shell wildcards and

Then call.

scp.get('/var/tmp/user-action*.*', ".")

**Comment by jbardin** [comment]
Looks like that doc needs to be updated.  Shell special characters are quoted by default now, with the exception of `~`.  You can change the behavior of the client by setting SCPClient.sanitize

**Comment by stonefury** [comment]
Thanks! Got it,

**Comment by remram44** [comment]
You can create an SCPClient that doesn't escape filenames, and then copy:
```python
scp = SCPClient(ssh.get_transport(),
                sanitize=lambda x: x)
scp.get('/var/tmp/data_patterm_*')
```
