### ISSUE TITLE
Any way to make this transfer more resilient?

### ISSUE THREAD

**Issue by axfelix** [jbardin/scp.py#54]
Hi,

I've been using this library for a little Python GUI client I've written for some of our depositors (I even managed to package it up into an executable for use on Windows, which was a real coup), and I'm generally very happy with it, but is there any way to make the transfer more resilient? A recursive directory transfer seems to be dying after around 64gb across a very fast local network. I know we're dealing with the limits of scp here, and it probably wouldn't be any easier to try to pack in an rsync or something, but if you have any ideas, I'd appreciate it!

**Comment by remram44** [comment]
> it probably wouldn't be any easier to try to pack in an rsync or something

Why? rsync sounds like a very good idea to me...

**Comment by axfelix** [comment]
It would be, if not for the headache of trying to deploy it on Windows within the little bit of GUI scaffolding I've already written ...

**Comment by remram44** [comment]
MSYS should provide a working rsync. But I'm with you on the packaging issues, this stuff is never fun...

**Comment by axfelix** [comment]
OK, fair enough :) I've done that song and dance with msys and nsis before for Windows clients, so I guess I'm just getting back on the horse. Thanks.
