### ISSUE TITLE
New package is needed on pypi to match documentation

### ISSUE THREAD

**Issue by scottbelden** [jbardin/scp.py#55]
This PR (https://github.com/jbardin/scp.py/commit/a57e68317f9503a54181a1e780391e09d431764e) was merged which updated the documentation according to that new code but a new package was never built.

**Comment by remram44** [comment]
It looks like the documentation on PyPI is still markdown, too.

**Comment by jbardin** [comment]
thanks for the reminder, I'll cut a new release in a bit...

**Comment by jbardin** [comment]
@remram44 , that rst doesn't seem to work on pypi 

(apparently [distutils bdist_wininst is broken](http://bugs.python.org/issue10945), so I'm having trouble upload a window binary too :angry: )

**Comment by remram44** [comment]
reStructuredText is possible, cf [gitobox](https://pypi.python.org/pypi/gitobox) :wink:

**Comment by jbardin** [comment]
strange, I'll have to poke at that later.

Dropping the windows bdist for a universal wheel, which seems to match what everyone else is doing ;)
