### ISSUE TITLE
put twice and more times, raise Channel closed.

### ISSUE THREAD

**Issue by yqnetwork** [jbardin/scp.py#56]
from paramiko import SSHClient
from scp import SCPClient

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect('example.com')

"""SCPCLient takes a paramiko transport as its only argument"""
scp = SCPClient(ssh.get_transport())

scp.put('test.txt', 'test2.txt')                                     ----------line  11
print "1"                                                                  ----------line  12
scp.get('test2.txt')                                                   ----------line  13
print "2"                                                                  ----------line  14
scp.put('test.txt', 'test3.txt')                                     ----------line  15
print "3"

scp.close()

:::::::::::::::::::::result::::::::::::::::::::::::::::
1
Channel closed.

    At line 13. will raise Channel closed. I found the exception is raised by paramiko/channel.py:_wait_for_event().Because "if self.event_ready:" is False.
    We has called exec_command in scp.put. Then I see the exec_command doc_string. It writed """When the command finishes executing, the channel will be closed and  can't be reused.  You must open a new channel if you wish to execute another command."""
    I don't known how about your tests. It run error in my pc. wish your help.

**Comment by jbardin** [comment]
hmm, this was caused by pull #53. I'm not sure how the example in the docs was run originally, but you're right that you can't reuse the channel between commands  :disappointed: 

I'll keep the context manager methods there for compatibility, but the channel will need to be closed between every command to be reliable.

**Comment by remram44** [comment]
If you can no longer send multiple files, every piece of code using scp will break. And this is on PyPI? This is really bad.

**Comment by jbardin** [comment]
yes, very.
At least the fix is simple. I have a patch and test
