### ISSUE TITLE
please include CHANGELOG.md in PyPI tarball

### ISSUE THREAD

**Issue by sandrotosi** [jbardin/scp.py#59]
HEllo,
it would be cool if you could include CHANGELOG.md in the next releases on PyPI

**Comment by remram44** [comment]
Some libraries appear to do this and some don't... Is it really useful?

**Comment by sandrotosi** [comment]
it is, at least from a downstream/distribution (debian) POV

**Comment by remram44** [comment]
Oh, right. Yes I can see they would want this.

Fixes with 98a5edc8.

**Comment by sandrotosi** [comment]
thanks, much appreciated!
