### ISSUE TITLE
"Tuple indices must be integers" on Windows

### ISSUE THREAD

**Issue by axfelix** [jbardin/scp.py#63]
Hi, not sure what this is about:

>>> bag_dir_parent
'C:\\Users\\Alex\\AppData\\Local\\Temp\tmpxniltb'
>>> remote_path
'~/deposit_here/324-444'
>>> scp.put(bag_dir_parent, remote_path, recursive="True")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\scp.py", line 143, in put
    scp_command = (b'scp -t ', b'scp -r -t ')[recursive]
TypeError: tuple indices must be integers, not str

This is newest scp.py from pip, in Python 2.7.3. If you don't have any idea what's going on I can try to update Python version or duplicate in OSX/Linux later on...

**Comment by remram44** [comment]
Looks like you passed a string for the 'recursive' parameter of put(). Don't do that.

**Comment by axfelix** [comment]
d'oh. thanks.

**Comment by axfelix** [comment]
different error after correcting that:

ERROR:paramiko.transport:Unknown exception: Unknown type
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\transport.py", line 1643, in run
ERROR:paramiko.transport:    self.auth_handler._handler_table[ptype](self.auth_handler, m)
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\auth_handler.py", line 229, in _parse_service_accept
ERROR:paramiko.transport:    m.add_string(self.username)
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\message.py", line 285, in add_string
ERROR:paramiko.transport:    s = asbytes(s)
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\common.py", line 170, in asbytes
ERROR:paramiko.transport:    raise Exception('Unknown type')
ERROR:paramiko.transport:Exception: Unknown type
ERROR:paramiko.transport:

this setup worked fine before trying to use the recursive option, FWIW.

**Comment by remram44** [comment]
Hard to tell from the code you didn't paste... what are the arguments?

**Comment by axfelix** [comment]
Sorry, same as the above example.

**Comment by remram44** [comment]
You didn't give the arguments above, what are `bag_dir_parent` and `remote_path`?

**Comment by axfelix** [comment]
bag_dir_parent
 'C:\Users\Alex\AppData\Local\Temp\tmpxniltb'
 remote_path
 '~/deposit_here/324-444'

**Comment by axfelix** [comment]
I can't seem to duplicate on OSX, so this is probably a Windows issue...

**Comment by remram44** [comment]
I'm gonna take a guess here and assume that you passed the wrong type, again, for the username or password. But really, I'm not gonna help you again if you don't paste some code.

**Comment by axfelix** [comment]
It's literally the same thing from my first comment except with recursive=True.

>>> bag_dir_parent
'C:\\Users\\Alex\\AppData\\Local\\Temp\tmpxniltb'
>>> remote_path
'~/deposit_here/324-444'
>>> scp.put(bag_dir_parent, remote_path, recursive="True")
ERROR:paramiko.transport:Unknown exception: Unknown type
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\transport.py", line 1643, in run
ERROR:paramiko.transport:    self.auth_handler._handler_table[ptype](self.auth_handler, m)
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\auth_handler.py", line 229, in _parse_service_accept
ERROR:paramiko.transport:    m.add_string(self.username)
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\message.py", line 285, in add_string
ERROR:paramiko.transport:    s = asbytes(s)
ERROR:paramiko.transport:  File "c:\Users\Alex\Dropbox\Python27\lib\site-packages\paramiko\common.py", line 170, in asbytes
ERROR:paramiko.transport:    raise Exception('Unknown type')
ERROR:paramiko.transport:Exception: Unknown type

Am I somehow being difficult?

**Comment by remram44** [comment]
> the username or password

I don't understand how you can fail to locate that.

**Comment by axfelix** [comment]
Oh, actually, you're right, those are probably QString :)

Sorry -- I got frustrated at you asking me for the same thing over again, and then didn't realize when you were actually raising something different.  Closing this!
