### ISSUE TITLE
Sending bytes directly

### ISSUE THREAD

**Issue by kimgr** [jbardin/scp.py#70]
I need to send file _content_ directly to a remote name over SCP.

I currently use this module by first creating a temporary file with the content and then copying said file, but it would be much nicer if I could do away with the logic and just pass the data directly.

Assuming this is not impossible for some reason, would you accept patches to that end?

**Comment by remram44** [comment]
This is not impossible 👍

I can't talk for jbardin but it sounds useful. Most Python APIs accept file-like objects in addition to filenames.

**Comment by einarf** [comment]
@kimgr It's fairly easy with paramiko now:
```python
client = paramiko.SSHClient(...)
client.connect(...)
sftp = client.open_sftp()
with sftp.open(full_path, 'w') as fd:
    fd.write(stuff)
```

where `stuff` is whatever you want to put in the file. In this case I'm just writing a text file, but you can do any kind of writing there. the `sftp.open()` method retuns a an object almost identical to the standard `open()`.

**Comment by kimgr** [comment]
@einarf -- thanks! I thought I had replied to this, but apparently not :-/

Looks nice, I'll try that when I have some time.
