### ISSUE TITLE
put after get results in corrupting file

### ISSUE THREAD

**Issue by telina** [jbardin/scp.py#74]
I got an issue copying a .tar.gz from a server to local and afterwardy copying that .tar.gz to another server. It seems like get command is not blocking or returns before the whole file is copied, so in the next step a file which is not fully copied yet gets copied to another server, which results in having a corrupted file.
I guess directly copying between the remote machiens would work - still trying to figure out how.

**Comment by remram44** [comment]
The `get()` function *does* block until the transfer is finished, so you might want to look deeper into the issue you are (were?) experiencing?

The SCP protocol doesn't support copying between servers (contrary to FTP, which you might want to consider).

**Comment by telina** [comment]
I'm sorry I checked the code and found that aswell. It was another issue on my side, which I wasn't able to see first.

Nevertheless copying between two remote machines would be a great feature :P

**Comment by remram44** [comment]
The SCP protocol doesn't support that, so there's nothing this library can do. You can check out [FTP server-to-server](https://en.wikipedia.org/wiki/File_eXchange_Protocol), which requires an FTP server on both ends but actually transfers the file directly (no data is sent to/from client).

**Comment by telina** [comment]
Well this works under Unix http://superuser.com/questions/686394/scp-between-two-remote-hosts-from-my-third-pc 
I am just disappointed about some Python libraries not being as powerful as the usual bash commands (for example ssh -X).

**Comment by remram44** [comment]
The data still transits on the client. The protocol simply doesn't support server-to-server.

I agree that there should be a way to do this without writing then reading back from the filesystem; I'll add an issue for this.
