### ISSUE TITLE
SSH session not active if connecting in a function

### ISSUE THREAD

**Issue by jluttine** [jbardin/scp.py#77]
Hi, thanks for this great package! I'm having an issue but I'm not sure if the problem is in scp or paramiko, perhaps you have some insight.

First, this works:
```
ssh = paramiko.SSHClient()
ssh.load_system_host_keys()
ssh.connect(hostname=HOST, username=USER, key_filename=KEY)
x = scp.SCPClient(ssh.get_transport())
with x as c:
    print(c)
```

But identical code where I have just moved the connection creation to a separate function doesn't work:
```
def get_client():
    ssh = paramiko.SSHClient()
    ssh.load_system_host_keys()
    ssh.connect(hostname=HOST, username=USER, key_filename=KEY)
    return scp.SCPClient(ssh.get_transport())
with get_client() as c:
    print(c)
```
I get the following error:
```
SSHException: SSH session not active
```

Am I doing something wrong here or is there a bug in scp or paramiko? Thanks for any help!

**Comment by remram44** [comment]
I'm assuming that paramiko might close the SSH connection when the `ssh = SSHClient()` object falls out of scope and is garbage-collected. You might have to keep a reference to it through other means...
