### ISSUE TITLE
Allow giving Path objects to get and put

### ISSUE THREAD

**Issue by cool-RR** [jbardin/scp.py#80]
Local paths may be either `PurePath` or `Path`, while remote paths must be `PurePath`.

**Comment by remram44** [comment]
You mean the remote path would be `PurePosixPath`, and the local path would be `Path`.

This is doable, and is probably a good idea since pathlib is now part of the standard library in Python 3.4+.

**Comment by remram44** [comment]
Closed by #164

**Comment by cool-RR** [comment]
Just shy of this bug's fifth birthday :) Thank you!
