### ISSUE TITLE
Put close in finally?

### ISSUE THREAD

**Issue by cool-RR** [jbardin/scp.py#81]
I'm debugging a few problems I have with this module, and if I understand correctly, if there's an exception in downloading or uploading files, you can't use the client object again. You get a "this channel is not open" error. If I'm not mistaken, that's because you try to reuse the dead channel instead of creating a new one. Could it be because you haven't put `self.close()` inside a `finally` clause?

**Comment by remram44** [comment]
Fixed by #90
