### ISSUE TITLE
IOError is masked by SCPException

### ISSUE THREAD

**Issue by nvgoldin** [jbardin/scp.py#82]
Hi,
this line https://github.com/jbardin/scp.py/blob/master/scp.py#L348 masks IOError exception  when no file or directory exists, which makes it hard to catch the exception:
```
  File "/home/ngoldin/virtualenv/lago-venv/lib/python2.7/site-packages/scp.py", line 198, in get
    self._recv_all()
  File "/home/ngoldin/virtualenv/lago-venv/lib/python2.7/site-packages/scp.py", line 348, in _recv_all
    raise SCPException(asunicode(msg[1:]))
SCPException: scp: /var/koko/bobo: No such file or directory
```
If I understand correctly, the docs state that all IOError errors should be thrown.

**Comment by remram44** [comment]
It doesn't really. There are places in the code where it does, but this particular line raised a SCPException for an error sent by the server.

**Comment by nvgoldin** [comment]
Ok, thanks for clarifying. Any special reason for this behaviour? Would it be (easily) possible to change it?
Currently what I did is run ``re.match`` on the exception, but I think that is fragile.

**Comment by remram44** [comment]
There is no standard for error codes in the SCP protocol, all you get is the human-readable string for server errors. scp.py cannot do better than your `re.match` unfortunately.
