### ISSUE TITLE
_open() method does not reopen a closed channel

### ISSUE THREAD

**Issue by YogeshLele** [jbardin/scp.py#89]
`._open()` only check if channel is `None` and not if channel is `closed`. Hence if `SCPException` that closes the channel the `._open()` method won't open it. Ref: Screenshot

![scp_py_bug](https://user-images.githubusercontent.com/5820571/28952357-4a30561e-7896-11e7-9aab-e8d5f4849e11.PNG)

**Comment by remram44** [comment]
Just to clarify, how do you ever get a closed channel? Using `close()` or the context manager should set it to None after closing the channel.

Or is it a timeout?

**Comment by YogeshLele** [comment]
This state is reached when the remote file/folder is not present and hence an `SCPException` is thrown. My application is constantly pulling files using scp and it only creates a new `SCPClient` when the underlying paramiko channel is broken. Hence this issue was returning False Positive.
