### ISSUE TITLE
[feature-request] Upload file-like objects from memory

### ISSUE THREAD

**Issue by nemesisdesign** [jbardin/scp.py#91]
Paramiko has a [putfo method](http://docs.paramiko.org/en/2.2/api/sftp.html#paramiko.sftp_client.SFTPClient.putfo) that allows uploading file-like objects.

Shall we add a similar method to this library as well? I need this feature to enable [openwisp2](https://github.com/openwisp/ansible-openwisp2) to push configurations to small routers that are not running an SFTP server by default. **OpenWISP 2** generates the configuration directly in memory, it can write to disk, but we avoid that as much as possible because it wouldn't scale for thousands of devices.

I'm willing to put effort in adding this feature, I hope to hear back from you and receive some guidance about the best way to do it.

As a starter, I'm looking at the [putfo method implementation in paramiko](https://github.com/paramiko/paramiko/blob/08f503740182608570ac87661225fe2e11914d8f/paramiko/sftp_client.py#L650-L689) although I'm not sure it can be replicated when I look at the implementation of [_send_files](https://github.com/jbardin/scp.py/blob/master/scp.py#L225-L255) in *scp.py*.

**Comment by remram44** [comment]
Duplicates #70. I think it's definitely a useful addition.
