### ISSUE TITLE
wildcard paths?

### ISSUE THREAD

**Issue by axfelix** [jbardin/scp.py#93]
Not sure what the best way to handle this is, but it seems like scp doesn't do it implicitly...

If I want to get a whole directory full of objects, but its parent directory name has a UUID appended to the known string, like:

scp /path/to/thing-I-know*/objects/

Is that a use case this module is intended to support? Or do I have to ssh in there first and try to figure out the directory name?

**Comment by remram44** [comment]
Duplicates #48

**Comment by axfelix** [comment]
Oops! Thanks.
