### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by dmsquires** [jbardin/scp.py#98]
Last update to PyPI is from May 2015, a PyPI update would be nice (especially for putfo)

**Comment by cglewis** [comment]
additionally, if the package was released as python2/python3 specific, right now it's only released as python2 even though it's python3 compatible.

**Comment by remram44** [comment]
@cglewis That's weird, there's a `py2.py3-none-any.whl` but it's tagged as `py2` on the PyPI page. Might be a PyPI bug. Anyhow it looks like pip downloads that wheel just fine, so it's not actually a problem.

**Comment by cglewis** [comment]
yeah, i only noticed it because pyup.io told me from using it as a dependency:
<img width="1375" alt="screen shot 2018-02-28 at 4 02 49 pm" src="https://user-images.githubusercontent.com/2931079/36813004-fcdee06a-1ca0-11e8-8726-93adc6ebfd73.png">

**Comment by remram44** [comment]
Updated [CHANGELOG](../blob/master/CHANGELOG.md).

@jbardin all ready if you want to do a release (just need to put a date in CHANGELOG.md)

**Comment by nemesisdesign** [comment]
@jbardin ping

**Comment by remram44** [comment]
0.11.0 is released!

**Comment by nemesisdesign** [comment]
Thanks a lot @remram44 and @jbardin for distributing pypi access.
